### ISSUE TITLE
Improve planning canvas

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/docs#14]
The [planning canvas](https://request-yo-racks.github.io/docs/contributor-zone/goals-strategy/) is currently ugly and not readable. It is an `svg` edited with [inkscape](https://inkscape.org) and exported as a `png`.

This file should receive some love and be updated so that people actually want to read its content.

**Comment by UX-Chris** [comment]
![ryr planning canvas](https://user-images.githubusercontent.com/33525135/37431373-11bf109c-27a3-11e8-8b32-85bd59cb5695.png)

I made this to replace the planning canvas a while ago. It should be readable now.

**Comment by rgreinho** [comment]
It looks great! Thanks for doing this! I'm looking forward to merge your PR!
